apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d76pjjdp7-nodejs 
  janus-idp.io/tekton: d76pjjdp7-nodejs
  backstage.io/kubernetes-id: d76pjjdp7-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d76pjjdp7-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  